import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const reviewStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'space-between',
    paddingTop: 24,
    paddingBottom: 8,
  },
  content: {
    gap: 16,
  },
  title: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
  },
  subtitle: {
    color: '#AAB3C7',
    fontSize: 13,
    fontWeight: '500',
    textAlign: 'center',
  },
  heroCard: {
    height: 322,
    borderRadius: 18,
    backgroundColor: '#4A1E1E',
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  heroImage: {
    ...StyleSheet.absoluteFillObject,
  },
  heroOverlay: {
    paddingHorizontal: 20,
    paddingBottom: 22,
    backgroundColor: 'rgba(63, 23, 23, 0.42)',
    gap: 6,
  },
  heroContent: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '500',
    textAlign: 'center',
  },
  heroDoer: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  todoTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  resultRow: {
    flexDirection: 'row',
    gap: 10,
  },
  resultButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#4B5568',
    backgroundColor: '#FCFCFD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rejectActive: {
    backgroundColor: '#FF4F7A',
    borderColor: '#FF4F7A',
  },
  approveActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  resultButtonText: {
    color: '#111318',
    fontSize: 16,
    fontWeight: '800',
  },
  feedbackCard: {
    minHeight: 74,
    borderRadius: 12,
    backgroundColor: '#252932',
    paddingHorizontal: 16,
    paddingVertical: 14,
    justifyContent: 'center',
  },
  feedbackText: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '500',
  },
  approveInput: {
    minHeight: 74,
    borderRadius: 12,
    backgroundColor: '#252932',
    paddingHorizontal: 16,
    paddingVertical: 14,
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
    textAlignVertical: 'top',
  },
  footer: {
    paddingTop: 16,
    paddingBottom: 10,
  },
  sendButton: {
    minHeight: 58,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonDisabled: {
    backgroundColor: '#4C5260',
  },
  sendButtonText: {
    color: '#111318',
    fontSize: 18,
    fontWeight: '800',
  },
  sendButtonTextDisabled: {
    color: '#9197A6',
  },
  modalOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.58)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 18,
    backgroundColor: '#2A2B31',
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 18,
  },
  closeButton: {
    alignSelf: 'flex-end',
    paddingHorizontal: 4,
  },
  closeText: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '500',
  },
  modalTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 2,
  },
  modalCaption: {
    color: '#AAB3C7',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 14,
    borderWidth: 1,
    borderColor: '#434A59',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  reasonInputWrap: {
    marginTop: 14,
    borderRadius: 12,
    backgroundColor: '#1D2027',
    paddingHorizontal: 16,
    paddingVertical: 14,
    minHeight: 146,
  },
  reasonInput: {
    flex: 1,
    minHeight: 98,
    color: colors.text,
    fontSize: 16,
    lineHeight: 22,
    textAlignVertical: 'top',
  },
  reasonCount: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'right',
    marginTop: 10,
  },
  modalPrimaryButton: {
    minHeight: 54,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
  },
  modalPrimaryButtonDisabled: {
    backgroundColor: '#4C5260',
  },
  modalPrimaryText: {
    color: '#111318',
    fontSize: 17,
    fontWeight: '800',
  },
});
