import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const groupJoinStyles = StyleSheet.create({
  flex: { flex: 1 },
  nav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 40,
  },
  back: { color: colors.text, fontSize: 24 },
  navTitle: { color: colors.text, fontSize: 18, fontWeight: '800' },
  navSpacer: { width: 24 },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.text,
    textAlign: 'center',
  },
  description: {
    color: colors.muted,
    lineHeight: 22,
    marginTop: 8,
    textAlign: 'center',
  },
  formSection: { marginTop: 48 },
  input: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: colors.surfaceLight,
    color: colors.text,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 16,
    fontWeight: '600',
  },
  inputFocused: { borderColor: colors.primary },
  button: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
    marginTop: 'auto',
  },
  buttonDisabled: { opacity: 0.45 },
  buttonText: { color: '#04210E', fontWeight: '800' },
  modalOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    width: '100%',
    borderRadius: 16,
    backgroundColor: colors.surface,
    padding: 20,
  },
  modalIcon: {
    alignSelf: 'center',
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#5B9DF0',
    color: '#111318',
    textAlign: 'center',
    lineHeight: 36,
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 14,
  },
  modalTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 10,
  },
  modalDesc: { color: '#8C91A7', textAlign: 'center', marginBottom: 18 },
  modalActions: { flexDirection: 'row', gap: 10 },
  modalButton: {
    flex: 1,
    height: 48,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonMuted: { backgroundColor: '#575B66' },
  modalButtonPrimary: { backgroundColor: '#5B9DF0' },
  modalButtonMutedText: { color: '#E5E7EE', fontWeight: '700' },
  modalButtonPrimaryText: { color: '#111318', fontWeight: '800' },
});
