import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const groupCreateStyles = StyleSheet.create({
  flex: { flex: 1 },
  nav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  back: { color: colors.text, fontSize: 24 },
  navTitle: { color: colors.text, fontSize: 18, fontWeight: '800' },
  navSpacer: { width: 24 },
  stepText: { color: '#5B9DF0', fontWeight: '800', marginBottom: 12 },
  title: { fontSize: 32, fontWeight: '800', color: colors.text, lineHeight: 40 },
  section: { marginTop: 28 },
  label: { color: '#D1D5E5', fontWeight: '700', marginBottom: 10 },
  spaced: { marginTop: 18 },
  input: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: colors.surfaceLight,
    color: colors.text,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 16,
    fontWeight: '600',
  },
  inputFocused: { borderColor: colors.primary },
  counterText: {
    color: '#8C91A7',
    position: 'absolute',
    right: 14,
    top: 16,
    fontSize: 12,
  },
  counterTextFocused: { color: colors.primary },
  counterBox: {
    height: 50,
    borderRadius: 12,
    backgroundColor: colors.surfaceLight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 6,
  },
  counterButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterButtonText: { color: colors.text, fontSize: 20, fontWeight: '800' },
  memberCount: { color: colors.text, fontSize: 16, fontWeight: '700' },
  counterGuide: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  counterGuideText: { color: '#8C91A7', fontSize: 12 },
  optionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  optionCard: {
    width: '47%',
    minHeight: 56,
    borderRadius: 12,
    backgroundColor: colors.surfaceLight,
    borderWidth: 1.5,
    borderColor: 'transparent',
    paddingHorizontal: 14,
    justifyContent: 'center',
  },
  startCard: {
    width: '47%',
    minHeight: 132,
    borderRadius: 12,
    backgroundColor: colors.surfaceLight,
    borderWidth: 1.5,
    borderColor: 'transparent',
    padding: 14,
    gap: 10,
  },
  optionCardActive: { borderColor: '#5B9DF0' },
  optionTitle: { color: colors.text, fontSize: 16, fontWeight: '800' },
  optionTitleActive: { color: colors.primary },
  calendarIcon: { fontSize: 16 },
  startDescription: { color: '#8C91A7', fontSize: 12, lineHeight: 18 },
  summaryWrap: { flex: 1, justifyContent: 'center' },
  summaryCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 18,
    marginHorizontal: 20,
  },
  summaryTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 18,
    textAlign: 'center',
  },
  summaryDivider: { height: 1, backgroundColor: colors.border, marginBottom: 16 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  summaryKey: { color: '#5B9DF0', fontWeight: '700' },
  summaryValue: { color: '#D1D5E5' },
  footer: { marginTop: 'auto', flexDirection: 'row', gap: 10, paddingTop: 18 },
  footerButton: {
    flex: 1,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    height: 52,
  },
  secondaryFooter: { backgroundColor: '#575B66' },
  primaryFooter: { backgroundColor: '#5B9DF0' },
  secondaryFooterText: { color: '#E5E7EE', fontWeight: '700' },
  primaryFooterText: { color: '#111318', fontWeight: '800' },
  buttonDisabled: { opacity: 0.35 },
  modalOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    width: '100%',
    borderRadius: 16,
    backgroundColor: colors.surface,
    padding: 20,
  },
  modalIcon: {
    alignSelf: 'center',
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#5B9DF0',
    color: '#111318',
    textAlign: 'center',
    lineHeight: 36,
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 14,
  },
  modalTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 10,
  },
  modalDesc: { color: '#8C91A7', textAlign: 'center', marginBottom: 18 },
  modalActions: { flexDirection: 'row', gap: 10 },
});
