import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { BAR_MAX_HEIGHT } from './utils';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  backButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backText: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '700',
  },
  screenTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
  },
  headerSpacer: {
    width: 32,
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  emptyCircle: {
    width: 156,
    height: 156,
    borderRadius: 78,
    borderWidth: 3,
    borderColor: '#757C95',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  emptyEmoji: {
    fontSize: 64,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 26,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 8,
  },
  emptyDescription: {
    color: colors.muted,
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 20,
  },
  primaryButton: {
    minWidth: 160,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  primaryButtonText: {
    color: '#111318',
    fontSize: 16,
    fontWeight: '800',
  },
  groupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  groupInfoArea: {
    flex: 1,
    paddingTop: 8,
  },
  groupNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
  },
  groupName: {
    color: '#4EA0FF',
    fontSize: 18,
    fontWeight: '800',
  },
  groupChevron: {
    color: colors.text,
    fontSize: 16,
  },
  metaRow: {
    flexDirection: 'row',
    gap: 18,
  },
  metaColumn: {
    gap: 2,
  },
  metaLabel: {
    color: '#8C91A7',
    fontSize: 11,
  },
  metaValue: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  characterWrap: {
    width: 92,
    height: 92,
    alignItems: 'center',
    justifyContent: 'center',
  },
  characterBody: {
    width: 78,
    height: 78,
    borderRadius: 30,
    backgroundColor: '#5B9DF0',
  },
  characterGlasses: {
    position: 'absolute',
    top: 28,
    width: 32,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#23252D',
  },
  characterLaptop: {
    position: 'absolute',
    bottom: 16,
    width: 46,
    height: 24,
    borderRadius: 6,
    backgroundColor: '#23252D',
  },
  chartCard: {
    backgroundColor: '#1E1F24',
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
  },
  cardIcon: {
    color: colors.text,
    fontSize: 16,
  },
  cardTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  badge: {
    minWidth: 106,
    backgroundColor: colors.primary,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  badgeText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '800',
  },
  badgePointer: {
    width: 0,
    height: 0,
    borderLeftWidth: 7,
    borderRightWidth: 7,
    borderTopWidth: 9,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: colors.primary,
    marginTop: -1,
    marginBottom: 2,
  },
  chartArea: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  axisColumn: {
    width: 18,
    height: BAR_MAX_HEIGHT,
    justifyContent: 'space-between',
  },
  axisText: {
    color: '#8C91A7',
    fontSize: 10,
    textAlign: 'right',
  },
  barRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: 10,
  },
  barColumn: {
    flex: 1,
    alignItems: 'center',
    gap: 6,
  },
  barVisualArea: {
    width: '100%',
    height: BAR_MAX_HEIGHT,
    position: 'relative',
    justifyContent: 'flex-end',
  },
  barTrack: {
    width: '100%',
    borderRadius: 12,
    backgroundColor: '#2A2B31',
    overflow: 'hidden',
    justifyContent: 'flex-end',
    position: 'absolute',
    bottom: 0,
  },
  barTrackPlaceholder: {
    width: '100%',
    height: 0,
  },
  barStripeWrap: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  barStripe: {
    position: 'absolute',
    top: -24,
    bottom: -24,
    width: 4,
    backgroundColor: 'rgba(255,255,255,0.10)',
    transform: [{ rotate: '28deg' }],
  },
  barFill: {
    width: '100%',
    borderRadius: 12,
    backgroundColor: '#92B8E8',
  },
  barFillCurrent: {
    backgroundColor: '#5B9DF0',
  },
  currentIndicator: {
    position: 'absolute',
    left: '50%',
    transform: [{ translateX: -53 }],
    alignItems: 'center',
    zIndex: 2,
  },
  currentDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#5B9DF0',
    borderWidth: 3,
    borderColor: '#F4F7FF',
    marginBottom: -9,
    zIndex: 1,
  },
  barLabel: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '700',
  },
  barLabelFuture: {
    color: '#8C91A7',
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 12,
  },
  infoCard: {
    flex: 1,
    minHeight: 148,
    backgroundColor: '#1E1F24',
    borderRadius: 16,
    padding: 16,
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 18,
  },
  infoIcon: {
    color: colors.text,
    fontSize: 14,
  },
  infoTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  infoSubText: {
    color: '#B1B7C9',
    fontSize: 13,
    marginBottom: 6,
  },
  rankValue: {
    color: '#4EA0FF',
    fontSize: 22,
    fontWeight: '800',
  },
  summaryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  summaryBullet: {
    color: '#DCE2F5',
    fontSize: 13,
    width: 18,
  },
  summaryItemText: {
    color: '#DCE2F5',
    fontSize: 13,
    fontWeight: '600',
  },
});
