import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const certificationStyles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  nav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  navBack: {
    color: colors.text,
    fontSize: 24,
    width: 24,
  },
  navTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  navSpacer: {
    width: 24,
  },
  imageBox: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  selectedImage: {
    width: '100%',
    height: '100%',
  },
  placeholderWrap: {
    alignItems: 'center',
    gap: 8,
  },
  placeholderEmoji: {
    fontSize: 72,
  },
  placeholderText: {
    color: colors.muted,
    fontSize: 13,
  },
  todoTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 18,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
  },
  mediaButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  mediaButtonText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  footerButton: {
    minHeight: 52,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    marginTop: 'auto',
  },
  footerButtonDisabled: {
    backgroundColor: '#5B6475',
  },
  footerButtonText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
  },
  title: {
    color: colors.text,
    fontSize: 26,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 24,
    marginBottom: 6,
  },
  noticeWrap: {
    alignSelf: 'center',
    minHeight: 28,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 42,
  },
  noticeIcon: {
    color: colors.muted,
    fontSize: 12,
  },
  noticeText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  textArea: {
    minHeight: 116,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: colors.text,
    fontSize: 15,
    textAlignVertical: 'top',
  },
  textAreaFocused: {
    borderColor: colors.primary,
  },
  textCounter: {
    position: 'absolute',
    right: 14,
    bottom: 12,
    color: colors.muted,
    fontSize: 12,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  modalCard: {
    width: '100%',
    borderRadius: 16,
    backgroundColor: '#2E3138',
    paddingHorizontal: 18,
    paddingVertical: 22,
    gap: 12,
  },
  modalIcon: {
    color: colors.primary,
    fontSize: 22,
    textAlign: 'center',
  },
  modalTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  modalDescription: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  modalButton: {
    flex: 1,
    minHeight: 42,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonMuted: {
    backgroundColor: '#575C67',
  },
  modalButtonPrimary: {
    backgroundColor: colors.primary,
  },
  modalButtonText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
});
