import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const mainStyles = StyleSheet.create({
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  logo: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '700',
  },
  profileButton: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileIcon: {
    color: colors.text,
    fontSize: 22,
  },
  groupSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  groupTextArea: {
    flex: 1,
    paddingTop: 8,
  },
  groupNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 14,
  },
  groupName: {
    color: '#4EA0FF',
    fontSize: 18,
    fontWeight: '800',
  },
  groupChevron: {
    color: colors.text,
    fontSize: 16,
    marginTop: 2,
  },
  groupMetaRow: {
    flexDirection: 'row',
    gap: 18,
  },
  metaColumn: {
    gap: 2,
  },
  metaLabel: {
    color: '#8C91A7',
    fontSize: 11,
  },
  metaValue: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  dosikWrap: {
    width: 92,
    height: 92,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dosikBody: {
    width: 78,
    height: 78,
    borderRadius: 30,
    backgroundColor: '#5B9DF0',
  },
  dosikLaptop: {
    position: 'absolute',
    bottom: 20,
    width: 48,
    height: 28,
    borderRadius: 6,
    backgroundColor: '#23252D',
  },
  progressHeader: {
    marginTop: 4,
    marginBottom: 6,
  },
  progressLabel: {
    color: '#8C91A7',
    fontSize: 11,
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    backgroundColor: '#1E212A',
    overflow: 'hidden',
    marginBottom: 16,
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#5B9DF0',
  },
  rankingButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#26272D',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 14,
  },
  rankingIcon: {
    color: '#5B9DF0',
    marginRight: 10,
    fontSize: 16,
  },
  rankingText: {
    flex: 1,
    color: '#D3D7E4',
    fontSize: 14,
    fontWeight: '600',
  },
  rankingChevron: {
    color: '#B7BDCF',
    fontSize: 22,
  },
  panel: {
    backgroundColor: '#1E1F24',
    borderRadius: 14,
    padding: 12,
    minHeight: 470,
  },
  dateHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  dateArrow: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: '#2A2C33',
  },
  dateArrowDisabled: {
    opacity: 0.35,
  },
  dateArrowText: {
    color: '#B7BDCF',
    fontSize: 18,
    fontWeight: '700',
  },
  dateTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#4A4E59',
    paddingHorizontal: 11,
    paddingVertical: 7,
    backgroundColor: 'transparent',
  },
  filterIcon: {
    color: '#8C91A7',
    fontSize: 10,
  },
  filterText: {
    color: '#9EA4B5',
    fontSize: 12,
    fontWeight: '700',
  },
  filterActiveText: {
    color: '#111318',
  },
  centerState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingTop: 36,
    paddingBottom: 24,
  },
  centerTitle: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 10,
  },
  centerDescription: {
    color: '#8C91A7',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 6,
  },
  primaryAction: {
    marginTop: 22,
    alignSelf: 'stretch',
    backgroundColor: '#5B9DF0',
    borderRadius: 12,
    alignItems: 'center',
    paddingVertical: 14,
  },
  primaryActionText: {
    color: '#111318',
    fontWeight: '800',
    fontSize: 16,
  },
  todayFigure: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 4,
  },
  todayChip: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  emptyFigure: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  emptyCircle: {
    width: 118,
    height: 118,
    borderRadius: 59,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  emptyEye: {
    position: 'absolute',
    top: 40,
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  emptyMouth: {
    marginTop: 20,
    width: 30,
    height: 14,
    borderBottomWidth: 3,
    borderRadius: 10,
  },
  doneFigure: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
  },
  doneBlob: {
    width: 88,
    height: 88,
    borderRadius: 32,
    backgroundColor: '#5B9DF0',
  },
  todoSection: {
    gap: 10,
  },
  todoRow: {
    minHeight: 56,
    borderRadius: 10,
    backgroundColor: '#2A2B31',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  todoRowMain: {
    flex: 1,
    minHeight: 56,
    paddingLeft: 14,
    paddingRight: 10,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  todoLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingRight: 12,
  },
  todoStatusBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  todoStatusBadgeText: {
    color: '#111318',
    fontSize: 9,
    fontWeight: '900',
  },
  todoContent: {
    color: '#E6E9F2',
    fontSize: 14,
    fontWeight: '600',
  },
  todoDimmed: {
    color: '#8C91A7',
  },
  certifyButton: {
    minWidth: 76,
    borderRadius: 8,
    backgroundColor: '#5B9DF0',
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignItems: 'center',
    marginRight: 12,
  },
  certifyButtonDisabled: {
    backgroundColor: '#595E6A',
  },
  certifyText: {
    color: '#111318',
    fontSize: 13,
    fontWeight: '800',
  },
  certifyTextDisabled: {
    color: '#A6ACBD',
  },
  rowChevron: {
    color: '#B7BDCF',
    fontSize: 22,
  },
  emptyFilterState: {
    minHeight: 280,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 12,
  },
  addTodoInline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
  },
  addTodoPlus: {
    color: '#8C91A7',
    fontSize: 18,
  },
  addTodoLabel: {
    color: '#8C91A7',
    fontSize: 14,
    fontWeight: '600',
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  groupSheet: {
    backgroundColor: '#2A2B31',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 28,
    minHeight: 420,
    maxHeight: 520,
    gap: 8,
  },
  groupSheetTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 10,
  },
  groupSheetScroll: {
    flexGrow: 0,
    maxHeight: 260,
  },
  groupSheetList: {
    gap: 8,
    paddingBottom: 12,
  },
  groupSheetRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  groupSheetText: {
    color: '#9EA4B5',
    fontSize: 17,
    fontWeight: '600',
  },
  groupSheetTextSelected: {
    color: '#4EA0FF',
    fontWeight: '800',
  },
  groupSheetCheck: {
    color: '#8BC0FF',
    fontSize: 20,
    fontWeight: '900',
    minWidth: 20,
    textAlign: 'right',
  },
  groupSheetFooter: {
    marginTop: 'auto',
    borderTopWidth: 1,
    borderTopColor: '#3A3D47',
    paddingTop: 14,
  },
  groupAddRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 32,
  },
  groupAddPlus: {
    color: '#C3C8D5',
    fontSize: 20,
  },
  groupAddText: {
    color: '#C3C8D5',
    fontSize: 17,
    fontWeight: '600',
  },
});
