import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const todoWriteStyles = StyleSheet.create({
  flex: { flex: 1 },
  nav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  back: { color: colors.text, fontSize: 24 },
  navTitle: { color: colors.text, fontSize: 18, fontWeight: '800' },
  navSpacer: { width: 24 },
  date: { color: '#9BA1B4', fontSize: 15, fontWeight: '600', marginBottom: 6 },
  limit: { color: colors.text, fontSize: 18, fontWeight: '800', marginBottom: 20 },
  limitCurrent: { color: colors.primary },
  limitTotal: { color: '#72788B' },
  inputRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  inputWrap: { flex: 1, position: 'relative' },
  input: {
    height: 50,
    borderRadius: 12,
    backgroundColor: colors.surfaceLight,
    color: colors.text,
    paddingLeft: 16,
    paddingRight: 56,
    borderWidth: 1,
    borderColor: 'transparent',
    fontSize: 15,
    fontWeight: '600',
  },
  inputFocused: { borderColor: colors.primary },
  inputDisabled: { backgroundColor: '#55585F', color: '#C4C8D4' },
  inputCount: {
    position: 'absolute',
    right: 12,
    top: 16,
    color: '#7F8598',
    fontSize: 12,
    fontWeight: '700',
  },
  addButton: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#575B66',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonEnabled: { backgroundColor: colors.primary },
  addButtonIcon: { color: '#E5E7EE', fontSize: 20, fontWeight: '800' },
  addButtonIconEnabled: { color: '#111318' },
  emptyState: { alignItems: 'center', marginTop: 92 },
  emptyFigure: {
    width: 128,
    height: 148,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  emptyCircle: {
    width: 96,
    height: 120,
    borderRadius: 48,
    borderWidth: 2,
    borderColor: '#7F8598',
  },
  emptyTitle: { color: '#D1D5E5', fontSize: 20, fontWeight: '800', marginBottom: 6 },
  emptyDesc: { color: '#7F8598', fontSize: 13 },
  todoList: { marginTop: 14, gap: 10 },
  todoRow: {
    minHeight: 52,
    borderRadius: 12,
    backgroundColor: colors.surface,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  todoRowLocked: {
    backgroundColor: '#22262F',
  },
  todoText: { flex: 1, color: colors.text, fontSize: 15, fontWeight: '700', marginRight: 12 },
  todoTextLocked: {
    color: '#7E8597',
  },
  removeIcon: { color: '#8B91A5', fontSize: 24, lineHeight: 24 },
  lockIcon: { color: '#E4C65A', fontSize: 18, lineHeight: 18 },
  saveButton: {
    marginTop: 'auto',
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
  },
  saveButtonDisabled: { backgroundColor: '#55585F' },
  saveButtonText: { color: '#111318', fontWeight: '800' },
  modalOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    width: '100%',
    borderRadius: 16,
    backgroundColor: colors.surface,
    padding: 20,
  },
  modalIcon: {
    alignSelf: 'center',
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    color: '#111318',
    textAlign: 'center',
    lineHeight: 36,
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 14,
  },
  modalTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 8,
  },
  modalDesc: {
    color: '#8C91A7',
    textAlign: 'center',
    marginBottom: 18,
  },
  modalActions: { flexDirection: 'row', gap: 10 },
  modalButton: {
    flex: 1,
    height: 48,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonMuted: { backgroundColor: '#575B66' },
  modalButtonPrimary: { backgroundColor: colors.primary },
  modalMutedText: { color: '#E5E7EE', fontWeight: '700' },
  modalPrimaryText: { color: '#111318', fontWeight: '800' },
});
